# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./api/
      
    - name: Build
      run: dotnet build --no-restore -warnaserror -c Release --verbosity m
      working-directory: ./api/
      
    - name: Test
      run: dotnet test --no-build -c Release --verbosity m
      working-directory: ./api/
